import type { Metadata } from "next"
import { getSession } from "@/lib/session"
import FormHandler from "@/components/form/FormHandler"
import Stripe from "stripe"

export const metadata: Metadata = {
  title: "Great Vibe Events - Form",
  description: "Generated by create next app",
}

export default async function Form({
  searchParams,
}: {
  searchParams: { payment_intent?: string }
}) {
  try {
    const { payment_intent } = searchParams
    if (!payment_intent) {
      return <span className="text-red-500">Invalid form data.</span>
    }

    if (process.env.STRIPE_SECRET_KEY === undefined) {
      throw new Error("Stripe secret key is not defined!")
    }

    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)
    const paymentIntent = await stripe.paymentIntents.retrieve(payment_intent)
    const userId = Number(paymentIntent.metadata.userId)
    const eventId = paymentIntent.metadata.eventId
    const event = await stripe.products.retrieve(eventId)
    const eventDate = Number(event.metadata.starts)
    const formCompleted = paymentIntent.metadata.formCompleted
    if (!userId || !eventId || !eventDate || !formCompleted) {
      return <span className="text-red-500">Invalid form data.</span>
    }

    const session = await getSession()

    if (userId !== session?.user?.id) {
      return <span className="text-red-500">Invalid form data.</span>
    }

    const now = Date.now()

    if (formCompleted === "true") {
      return (
        <span className="text-green-500">You have completed this form.</span>
      )
    }

    if (now > eventDate) {
      return (
        <span className="text-red-500">
          Form cannot be completed because the event has already started.
        </span>
      )
    }

    return (
      <>
        <b className="text-center">PARTICIPATION AND RELEASE FORM</b>
        <p className="w-full lg:w-[500px] ml-auto mr-auto">
          FORM MUST BE COMPLETED AND SIGNED BY ALL PARTIES PRIOR TO
          PARTICIPATING IN GREAT VIBE EVENTS ORGANIZED FUNCTIONS
        </p>
        <FormHandler paymentIntent={payment_intent} />
      </>
    )
  } catch (error: any) {
    console.error(error)
    if (error.type === "StripeInvalidRequestError") {
      return <span className="text-red-500">{error.raw.message}</span>
    } else {
      return <span className="text-red-500">Internal server error</span>
    }
  }
}
