import type { Metadata } from "next"
import { getEventById, getEventPayment } from "@/actions/server"
import { getSession } from "@/lib/session"
import FormHandler from "@/components/form/FormHandler"
import Stripe from "stripe"

export const metadata: Metadata = {
  title: "Great Vibe Events - Form",
  description: "Generated by create next app",
}

export default async function Form({
  searchParams,
}: {
  searchParams: { payment_intent?: string }
}) {
  try {
    const { payment_intent } = searchParams
    if (!payment_intent) {
      return <span className="text-red-500">Invalid form data.</span>
    }

    if (process.env.STRIPE_SECRET_KEY === undefined) {
      throw new Error("Stripe secret key is not defined!")
    }

    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)
    const paymentIntent = await stripe.paymentIntents.retrieve(payment_intent)
    const userId = Number(paymentIntent.metadata.userId)
    const session = await getSession()

    if (userId !== session?.user?.id) {
      return <span className="text-red-500">Invalid form data.</span>
    }

    const eventId = paymentIntent.metadata.eventId
    const event = await getEventById(eventId)
    if (!event) {
      return <span className="text-red-500">Event not found.</span>
    }

    const today = new Date()
    const eventDate = new Date(event.date)
    const timeFormatter = new Intl.DateTimeFormat("en-US", {
      hour: "numeric",
      minute: "numeric",
      second: "numeric",
      hour12: false,
    })
    const currentTime = timeFormatter.format(today)

    if (
      today > eventDate ||
      (today === eventDate && currentTime >= event.start_time)
    ) {
      return (
        <span className="text-red-500">
          Form cannot be completed because the event has already started.
        </span>
      )
    }

    const eventPayment = await getEventPayment(event.id)
    if (eventPayment?.form_completed) {
      return (
        <span className="text-green-500">You have completed this form.</span>
      )
    }

    return (
      <>
        <b className="text-center">PARTICIPATION AND RELEASE FORM</b>
        <p className="w-full lg:w-[500px] ml-auto mr-auto">
          FORM MUST BE COMPLETED AND SIGNED BY ALL PARTIES PRIOR TO
          PARTICIPATING IN GREAT VIBE EVENTS ORGANIZED FUNCTIONS
        </p>
        <FormHandler paymentIntent={payment_intent} />
      </>
    )
  } catch (error: any) {
    console.error(error)
    if (error.type === "StripeInvalidRequestError") {
      return <span className="text-red-500">{error.raw.message}</span>
    } else {
      return <span className="text-red-500">Internal server error</span>
    }
  }
}
