import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import Faq from "@/components/about/Faq"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faCaretDown, faCaretUp } from "@fortawesome/free-solid-svg-icons"
import { Open_Sans } from "next/font/google"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - About",
  description: "Generated by create next app",
}

export default function About() {
  return (
    <>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mb-8 ml-3 xl:ml-0`}
      >
        WHO WE ARE
      </span>
      <Image
        src={"/about.png"}
        alt="about_image"
        width={0}
        height={0}
        sizes="100%"
        className="w-full h-auto mr-auto ml-auto object-contain"
        priority
      />
      <div
        className={`bg-[#DAFFC0] p-10 ml-auto mr-auto w-full ${openSans.className} xl:mb-12`}
      >
        <span className="text-center text-2xl mb-4 w-full block">
          Our Mission
        </span>
        <p className={`text-lg text-[#575757] ${openSans.className}`}>
          Our mission at Great Vibe Events is to empower people with mental and
          physical disabilities to live fulfilling and joyful lives. We believe
          that everyone deserves to have positive and meaningful experiences,
          regardless of their abilities or challenges. That's why we organize a
          variety of events and activities that are accessible, inclusive, and
          fun for people with disabilities aged 18 and above. Whether it's
          socializing with peers, learning new skills, or improving their health
          and well-being, our participants can find something that suits their
          needs and interests at Great Vibe Events. We are a nonprofit
          organization that relies on the support of our volunteers, donors, and
          partners to make our events possible. Join us today and help us create
          a more vibrant and compassionate community for people with
          disabilities an opportunity to thrive, regardless of their background
          or circumstances.
        </p>
      </div>
      <div className="flex flex-col xl:flex-row xl:gap-2">
        <div className={`bg-[#DAFFC0] ${openSans.className} w-full xl:w-1/2`}>
          <Image
            src={"/company_values.png"}
            alt="company_values"
            width={0}
            height={0}
            sizes="100%"
            className="w-full h-auto mr-auto ml-auto object-contain"
          />
          <div className="p-10">
            <span className="text-center text-2xl mb-4 w-full block">
              Our Values
            </span>
            <p className={`text-lg text-[#575757] ${openSans.className}`}>
              At Great Vibe Events, we believe that everyone deserves to have
              fun, learn new skills, and connect with others. Our values are:
            </p>
            <ul
              className={`text-lg list-inside list-disc text-[#575757] ${openSans.className}`}
            >
              <li>
                Inclusion: We welcome people with disabilities of all kinds,
                backgrounds, and abilities. We respect and celebrate diversity
                and individuality.
              </li>
              <li>
                Empowerment: We help people with disabilities to discover their
                strengths, overcome their challenges, and achieve their goals.
                We provide opportunities for personal growth and development.
              </li>
              <li>
                Collaboration: We work together with people with disabilities,
                their families, and other stakeholders to create events and
                activities that meet their needs and preferences. We foster a
                sense of community and belonging.
              </li>
              <li>
                Innovation: We constantly seek new ways to improve our services
                and deliver high-quality experiences. We embrace creativity and
                adaptability.
              </li>
              <li>
                Joy: We create a positive and supportive environment where
                people with disabilities can have fun, relax, and enjoy
                themselves. We celebrate every achievement and success.
              </li>
            </ul>
          </div>
        </div>
        <div className={`bg-[#DAFFC0] ${openSans.className} w-full xl:w-1/2`}>
          <Image
            src={"/company_team.png"}
            alt="company_team"
            width={0}
            height={0}
            sizes="100%"
            className="w-full h-auto mr-auto ml-auto object-contain"
            priority
          />
          <div className="p-10">
            <span className="text-center text-2xl mb-4 w-full block">
              Our Team
            </span>
            <p className={`text-lg text-[#575757] ${openSans.className}`}>
              At Great Vibe Events, we believe that everyone deserves to have
              fun and fulfilling experiences, regardless of their abilities.
              That's why we are dedicated and passionate about creating events
              and activities that are accessible, inclusive, and enjoyable for
              people with disabilities aged 18 and above. Whether it's a social
              gathering, a healthy eating workshop, a fitness class, or a mental
              skills training, we make sure that each event is tailored to the
              specific needs and preferences of our participants. Our goal is to
              help people with disabilities discover new possibilities, learn
              new skills, and connect with others who share their interests.
              Join us today and experience the great vibe that we create
              together!
            </p>
          </div>
        </div>
      </div>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mt-16 ml-3 xl:ml-0`}
      >
        FREQUENTLY ASKED QUESTIONS
      </span>
      <p
        className={`text-[#575757] text-lg ${openSans.className} mt-4 ml-3 xl:ml-0`}
      >
        Please reach us at
        <Link
          href={"mailto:info@greatvibeevents.org"}
          className="text-[#49740B]"
        >
          &nbsp;info@greatvibeevents.org&nbsp;
        </Link>
        if you cannot find an answer to your question.
      </p>
      <Faq />
      <div className="bg-black text-white border-yellow-500 border-2 box-border w-full h-[90px] mt-8 mb-8">
        <span>content ad space</span>
      </div>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mb-8 ml-3 xl:ml-0`}
      >
        GREAT VIBE EVENTS-THE DRIVING FORCE
      </span>
      <span
        className={`text-2xl text-[#575757] ${openSans.className} ml-3 xl:ml-0`}
      >
        Meet the Boone's : A story of love, loss, and service
      </span>
      <p
        className={`text-lg text-[#575757] ${openSans.className} block mt-6 ml-3 xl:ml-0`}
      >
        Jimmy, Andy and Mark Boone are brothers who have dedicated their lives
        to helping people with disabilities.
      </p>
      <p
        className={`text-lg text-[#575757] ${openSans.className} block mt-6 ml-3 xl:ml-0`}
      >
        Their desire to be involved with the intellectually and physically
        disabled community transpired from the love of their sister, Faith
        Boone, who was born with Down Syndrome and passed away at a very young
        age from heart disease. Faith's impact on her brothers' lives was
        immediate and profound.
      </p>
      <p
        className={`text-lg text-[#575757] ${openSans.className} block mt-6 ml-3 xl:ml-0`}
      >
        The Boone’s started volunteering with Best Buddies. They enjoyed
        mentoring and received great pleasure when their buddies would achieve
        their goals. The Boone's also learned valuable lessons in compassion,
        empathy, and determination. After high school, Jimmy began working at
        Jills House, a nonprofit that provides short term overnight respite care
        for families raising children with intellectual disabilities. Jimmy then
        teamed up with Andy & Mark, as instructors for an evening Adaptive
        fitness course offered at Fairfax County, where they still enjoy
        teaching today.
      </p>
      <p
        className={`text-lg text-[#575757] ${openSans.className} block mt-6 ml-3 xl:ml-0`}
      >
        The Boone’s realized social events for adults with intellectual
        disabilities are lacking and Great Vibes Events was created. Great Vibes
        offers a safe place for adults aged 18 and older to gather, learn,
        exchange ideas, acquire new skills and participate in fun activities.
      </p>
      <div className="bg-black text-white border-yellow-500 border-2 box-border w-full h-[90px] mt-8 mb-8">
        <span>content ad space</span>
      </div>
      <div className="flex flex-wrap w-full gap-4">
        <div className="bg-black p-3">
          <span className="text-white">Team Member 1</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 2</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 3</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 4</span>
        </div>
      </div>
      <div className="bg-black text-white border-yellow-500 border-2 box-border w-full h-[90px] mt-8 mb-8">
        <span>content ad space</span>
      </div>
      <div className="flex flex-wrap w-full gap-4">
        <div className="bg-black p-3">
          <span className="text-white">Partner space 1</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 2</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 3</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 4</span>
        </div>
      </div>
    </>
  )
}
