import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import Faq from "@/components/about/Faq"
import { Open_Sans } from "next/font/google"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - About",
  description: "Generated by create next app",
}

export default function About() {
  return (
    <>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mb-8 ml-3 xl:ml-0`}
      >
        FAITH BOONE, THE DRIVING FORCE BEHIND GREAT VIBE EVENTS
      </span>
      <div className="flex flex-col mb-10 lg:flex-row">
        <div className="flex-1 order-2 lg:order-1">
          <span className={`${openSans.className} text-2xl text-center block`}>
            Meet the Boone's : A story of love, loss, and service
          </span>
          <span
            className={`block mt-4 text-center text-lg ${openSans.className} text-[#5e5e5e]`}
          >
            Susan, Jim and their sons Jimmy, Andy and Mark Boone have dedicated
            their lives to helping people with disabilities.
          </span>
          <p
            className={`text-[#5e5e5e] text-center text-lg ${openSans.className} mt-8`}
          >
            Their desire to be involved with the intellectually and physically
            disabled community transpired from the love of their Daughter and
            Sister, Faith Boone. Faith was born with Down Syndrome and passed
            away at a very young age of 3 from complications due to a heart
            defect. Faith's impact on the Boone's entire family was immediate
            and profound.
          </p>
          <p
            className={`text-[#5e5e5e] text-center text-lg ${openSans.className}`}
          >
            The Boone’s started volunteering with Best Buddies. They enjoyed
            mentoring and received great pleasure when their buddies would
            achieve their goals. The Boone's also learned valuable lessons in
            compassion, empathy, and determination.
          </p>
          <p
            className={`text-[#5e5e5e] text-center text-lg ${openSans.className}`}
          >
            The Boone’s realized social events for adults with intellectual and
            physical disabilities are lacking and Great Vibes Events was created
            to provide fun social events for the adult community. Great Vibe
            Events offers a safe place for adults aged 18 and older to gather,
            learn, exchange ideas, acquire new skills and participate in fun
            social activities.
          </p>
        </div>
        <div className="w-full lg:w-[400px] h-fit lg:ml-8 relative order-1 lg:order-2">
          <Image
            src={"/img/faith.png"}
            height={0}
            width={0}
            sizes="(min-width: 1024) 100%, 100vw "
            alt="logo_welcome"
            className="w-full h-auto mr-auto ml-auto object-contain"
            priority
          />
          <span
            className={`${openSans.className} text-base text-[#525252] text-center mb-6 lg:text-left lg:pl-3 block bg-[#DAFFC0] mt-8 lg:mt-0 lg:mb-0`}
          >
            Faith Boone- Our driving force behind Great Vibe Events
          </span>
        </div>
      </div>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mt-10 mb-8 ml-3 xl:ml-0`}
      >
        WHO WE ARE
      </span>
      <Image
        src={"/img/about.png"}
        alt="about_image"
        width={0}
        height={0}
        sizes="100vw"
        className="w-full h-auto mr-auto ml-auto object-contain"
        priority
      />
      <div
        className={`bg-[#DAFFC0] p-10 ml-auto mr-auto w-full ${openSans.className} xl:mb-12`}
      >
        <span className="text-center text-2xl mb-4 w-full block">
          Our Mission
        </span>
        <p className={`text-lg text-[#575757] ${openSans.className}`}>
          Our mission at Great Vibe Events is to empower people with mental and
          physical disabilities to live fulfilling and joyful lives. We believe
          that everyone deserves to have positive and meaningful experiences,
          regardless of their abilities or challenges. That's why we organize a
          variety of events and activities that are accessible, inclusive, and
          fun for people with disabilities aged 18 and above. Whether it's
          socializing with peers, learning new skills, or improving their health
          and well-being, our participants can find something that suits their
          needs and interests at Great Vibe Events. We are a nonprofit
          organization that relies on the support of our volunteers, donors, and
          partners to make our events possible. Join us today and help us create
          a more vibrant and compassionate community for people with
          disabilities an opportunity to thrive, regardless of their background
          or circumstances.
        </p>
      </div>
      <div className="flex flex-col md:flex-row md:gap-2">
        <div
          className={`bg-[#DAFFC0] ${openSans.className} w-full mt-14 xl:mt-0 lg:w-1/2`}
        >
          <Image
            src={"/img/company_values.png"}
            alt="company_values"
            width={0}
            height={0}
            sizes="(max-width: 768px) 100vw, (min-width: 769px) 50vw"
            className="w-full h-auto mr-auto ml-auto object-contain"
          />
          <div className="p-10">
            <span className="text-center text-2xl mb-4 w-full block">
              Our Values
            </span>
            <p className={`text-lg text-[#575757] ${openSans.className}`}>
              At Great Vibe Events, we believe that everyone deserves to have
              fun, learn new skills, and connect with others. Our values are:
            </p>
            <ul
              className={`text-lg list-inside list-disc text-[#575757] ${openSans.className}`}
            >
              <li>
                Inclusion: We welcome people with disabilities of all kinds,
                backgrounds, and abilities. We respect and celebrate diversity
                and individuality.
              </li>
              <li>
                Empowerment: We help people with disabilities to discover their
                strengths, overcome their challenges, and achieve their goals.
                We provide opportunities for personal growth and development.
              </li>
              <li>
                Collaboration: We work together with people with disabilities,
                their families, and other stakeholders to create events and
                activities that meet their needs and preferences. We foster a
                sense of community and belonging.
              </li>
              <li>
                Innovation: We constantly seek new ways to improve our services
                and deliver high-quality experiences. We embrace creativity and
                adaptability.
              </li>
              <li>
                Joy: We create a positive and supportive environment where
                people with disabilities can have fun, relax, and enjoy
                themselves. We celebrate every achievement and success.
              </li>
            </ul>
          </div>
        </div>
        <div
          className={`bg-[#DAFFC0] ${openSans.className} w-full mt-14 xl:mt-0 lg:w-1/2`}
        >
          <Image
            src={"/img/company_team.png"}
            alt="company_team"
            width={0}
            height={0}
            sizes="(max-width: 768px) 100vw, (min-width: 769px) 50vw"
            className="w-full h-auto mr-auto ml-auto object-contain"
            priority
          />
          <div className="p-10">
            <span className="text-center text-2xl mb-4 w-full block">
              Our Team
            </span>
            <p className={`text-lg text-[#575757] ${openSans.className}`}>
              At Great Vibe Events, we believe that everyone deserves to have
              fun and fulfilling experiences, regardless of their abilities.
              That's why we are dedicated and passionate about creating events
              and activities that are accessible, inclusive, and enjoyable for
              people with disabilities aged 18 and above. Whether it's a social
              gathering, a healthy eating workshop, a fitness class, or a mental
              skills training, we make sure that each event is tailored to the
              specific needs and preferences of our participants. Our goal is to
              help people with disabilities discover new possibilities, learn
              new skills, and connect with others who share their interests.
              Join us today and experience the great vibe that we create
              together!
            </p>
          </div>
        </div>
      </div>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mt-16 ml-3 xl:ml-0`}
      >
        FREQUENTLY ASKED QUESTIONS
      </span>
      <p
        className={`text-[#575757] text-lg ${openSans.className} mt-4 ml-3 xl:ml-0`}
      >
        Please reach us at
        <Link
          href={"mailto:info@greatvibeevents.org"}
          className="text-[#49740B]"
        >
          &nbsp;info@greatvibeevents.org&nbsp;
        </Link>
        if you cannot find an answer to your question.
      </p>
      <Faq />
      <div className="bg-black text-white border-yellow-500 border-2 box-border w-full h-[90px] mt-8 mb-8">
        <span>content ad space</span>
      </div>
      <div className="flex flex-wrap w-full gap-4">
        <div className="bg-black p-3">
          <span className="text-white">Team Member 1</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 2</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 3</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Team Member 4</span>
        </div>
      </div>
      <div className="bg-black text-white border-yellow-500 border-2 box-border w-full h-[90px] mt-8 mb-8">
        <span>content ad space</span>
      </div>
      <div className="flex flex-wrap w-full gap-4">
        <div className="bg-black p-3">
          <span className="text-white">Partner space 1</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 2</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 3</span>
        </div>
        <div className="bg-black p-3">
          <span className="text-white">Partner space 4</span>
        </div>
      </div>
    </>
  )
}
