import type { Metadata } from "next"
import "./globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { CheckoutDataProvider } from "@/context/CheckoutDataProvider"
import { getSession } from "@/lib/session"

export const metadata: Metadata = {
  title:
    "Great Vibe Events - Empowering Individuals with Intellectual Disabilities",
  description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <CheckoutDataProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <div className={`flex flex-col 2xl:flex-row`}>
            <div
              className={`box-border h-[90px] w-full border-2 border-yellow-500 bg-black 2xl:h-auto 2xl:w-[160px]`}
            >
              <span className="text-white">[ad container left]</span>
            </div>
            <div className="ml-auto mr-auto flex w-full flex-col pl-6 pr-6 lg:w-[1000px] xl:w-[1160px] 2xl:w-[1232px]">
              <div className="hidden h-[90px] w-full bg-black 2xl:inline-block">
                <span className="text-white">[ad container middle]</span>
              </div>
              <Navbar session={session} />
              {children}
              <Footer />
            </div>
            <div
              className={`box-border h-[90px] w-full border-2 border-yellow-500 bg-black 2xl:h-auto 2xl:w-[160px]`}
            >
              <span className="text-white">[ad container right]</span>
            </div>
          </div>
        </body>
      </html>
    </CheckoutDataProvider>
  )
}
