import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title:
    "Great Vibe Events - Empowering Individuals with Intellectual Disabilities",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <span className="w-full block text-center pt-3">[ad space]</span>
        <span className="w-full block text-left pl-3">[ad space]</span>
        <span className="w-full block text-right pr-3">[ad space]</span>
        <Navbar />
        <div className="flex flex-col w-[1232px] ml-auto mr-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
