import type { Metadata } from "next"
import "./globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import ContentWrapper from "@/components/ContentWrapper"

export const metadata: Metadata = {
  title:
    "Great Vibe Events - Empowering Individuals with Intellectual Disabilities",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <ContentWrapper>{children}</ContentWrapper>
}
