import type { Metadata } from "next"
import Gallery from "@/components/gallery/Gallery"
import { getGalleryImageUrls } from "@/actions/server"
import { Open_Sans } from "next/font/google"
import { EdgeStoreProvider } from "@/lib/edgestore"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - Gallery",
  description: "Generated by create next app",
}

export default async function GalleryPage() {
  let imageUrls
  let error
  try {
    imageUrls = await getGalleryImageUrls(8)
  } catch (e: any) {
    error = e.message
  }
  return (
    <EdgeStoreProvider>
      <h1 className={`ml-auto mr-auto text-2xl ${openSans.className}`}>
        Welcome
      </h1>
      <span
        className={`text-gray-500 text-lg ml-auto mr-auto ${openSans.className}`}
      >
        Great People+New Friends+Great Activities=Great Vibes
      </span>
      {imageUrls && <Gallery images={imageUrls.items} />}
      {error && (
        <span className="text-red-500 block mt-3">{error.message}</span>
      )}
    </EdgeStoreProvider>
  )
}
