import type { Metadata } from "next"
import GalleryLoader from "@/components/gallery/GalleryLoader"
import { Open_Sans } from "next/font/google"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - Gallery",
  description: "Generated by create next app",
}

export default function Gallery() {
  return (
    <>
      <h1 className={`ml-auto mr-auto text-2xl ${openSans.className}`}>
        Welcome
      </h1>
      <span
        className={`text-gray-500 text-lg ml-auto mr-auto ${openSans.className}`}
      >
        Great People+New Friends+Great Activities=Great Vibes
      </span>
      <GalleryLoader />
    </>
  )
}
