import type { Metadata } from "next"
import StripeLoader from "@/components/checkout/StripeLoader"
import { getProduct } from "@/lib/stripe"

export const metadata: Metadata = {
  title: "Great Vibe Events - Checkout",
  description: "Generated by create next app",
}

export default async function Checkout({
  searchParams,
}: {
  searchParams: {
    product_id?: string
  }
}) {
  try {
    if (!searchParams.product_id) {
      return <span className="text-red-500">Invalid event data.</span>
    }

    const event = await getProduct(searchParams.product_id)

    if (!event) {
      return <span className="text-red-500">Event not found.</span>
    }

    const now = Date.now()
    const eventDate = Number(event.metadata.starts)
    const eventEnds = Number(event.metadata.ends)
    const eventAddress = event.metadata.address

    if (now > eventDate) {
      return (
        <span className="text-red-500">
          Event ticket is not available for purchase.
        </span>
      )
    }
    return (
      <StripeLoader
        name={event.name}
        starts={eventDate}
        ends={eventEnds}
        address={eventAddress}
        eventId={event.id}
      />
    )
  } catch (error: any) {
    console.error(error)
    if (error.type === "StripeInvalidRequestError") {
      return <span className="text-red-500">{error.raw.message}</span>
    } else {
      return <span className="text-red-500">Internal server error</span>
    }
  }
}
