import type { Metadata } from "next"
import LoginHandler from "@/components/login/LoginHandler"

export const metadata: Metadata = {
  title: "Great Vibe Events - Login",
  description: "Generated by create next app",
}

export default function Login() {
  return <LoginHandler />
}
