import type { Metadata } from "next"
import QuoteSlider from "@/components/home/QuoteSlider"
import VolunteerForm from "@/components/volunteer/VolunteerForm"
import { Open_Sans } from "next/font/google"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - Volunteer",
  description: "Generated by create next app",
}

export default function Volunteer() {
  return (
    <>
      <span
        className={`text-[#49740B] text-lg ${openSans.className} mt-10 ml-3 xl:ml-0`}
      >
        VOLUNTEER
      </span>
      <span className="mt-3 mb-3">[volunteer description]</span>
      <QuoteSlider />
      <VolunteerForm />
      <div className="mt-3 flex flex-wrap gap-3 justify-center">
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
        <div className="bg-black w-[180px] h-[150px]">
          <span className="text-white">sponsor space</span>
        </div>
      </div>
    </>
  )
}
