import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Great Vibe Events - Shop",
  description: "Generated by create next app",
}

export default function Shop() {
  return (
    <span
      className={`text-[#49740B] text-lg ${openSans.className} mt-10 ml-3 xl:ml-0`}
    >
      GREAT VIBE SHOP
    </span>
  )
}
